### ISSUE TITLE
想請教一下加入 if then else 問題

### ISSUE THREAD

**Issue by DLHC** [hkargv/paipan#1]
大大您好，是这样的

我在尝试加入代码，把当 “年柱” 是己亥的时候，就输出 "你好吗"；当 “年柱” 是庚子的时候，就输出 "我很好"；当 “年柱” 是辛丑的时候，就输出 "他好好"。於是在 index.html 页面的这

```
	var [tg, dz] = p.GetGZ(yy, mm , dd, hh, mt, ss);
	txt += "对应的干支历:"+p.ctg[tg[0]]+p.cdz[dz[0]]+p.ctg[tg[1]]+p.cdz[dz[1]]+p.ctg[tg[2]]+p.cdz[dz[2]]+p.ctg[tg[3]]+p.cdz[dz[3]]+"\n";
```

句下面，加入了

```
	var test123 = p.ctg[tg[0]]+p.cdz[dz[0]];
	if(test123 = "己亥"){
	txt += "你好吗";
	} else if (test123 = "庚子") {
	txt += "我很好";
	} else if (test123 = "辛丑") {
	txt += "他好好";
	}
```

不过得出的结果是直接就输出了 "你好吗"，而且一直都是显示 "你好吗"，不管我在下拉选单选择 2020(庚子年) 或是 2021(辛丑年) ，它都是维持在 "你好吗"，不懂得转换至 "我很好"丶"他好好" @@

可以请教一吓我错在那里吗？感谢您

**Comment by hkargv** [comment]
if(test123 == "己亥"){
txt += "你好吗";
} else if (test123 == "庚子") {
txt += "我很好";
} else if (test123 == "辛丑") {
txt += "他好好";
}


hkargv@139.com
 
发件人： DLHC
发送时间： 2020-06-07 23:49
收件人： hkargv/paipan
抄送： Subscribed
主题： [hkargv/paipan] 想請教一下加入 if then else 問題 (#1)
大大您好，是这样的
我在尝试加入代码，把当 “年柱” 是己亥的时候，就输出 "你好吗"；当 “年柱” 是庚子的时候，就输出 "我很好"；当 “年柱” 是辛丑的时候，就输出 "他好好"。於是在 index.html 页面的这
var [tg, dz] = p.GetGZ(yy, mm , dd, hh, mt, ss); txt += "对应的干支历:"+p.ctg[tg[0]]+p.cdz[dz[0]]+p.ctg[tg[1]]+p.cdz[dz[1]]+p.ctg[tg[2]]+p.cdz[dz[2]]+p.ctg[tg[3]]+p.cdz[dz[3]]+"\n"; 
句下面，加入了
` var test123 = p.ctg[tg[0]]+p.cdz[dz[0]];
if(test123 = "己亥"){
txt += "你好吗";
} else if (test123 = "庚子") {
txt += "我很好";
} else if (test123 = "辛丑") {
txt += "他好好";
}

`
不过得出的结果是直接就输出了 "你好吗"，而且一直都是显示 "你好吗"，不管我在下拉选单选择 2020(庚子年) 或是 2021(辛丑年) ，它都是维持在 "你好吗"，不懂得转换至 "我很好"丶"他好好" @@
可以请教一吓我错在那里吗？感谢您

**Comment by ghost** [comment]
test123 = "己亥"

改成

test123 == "己亥"

**Comment by DLHC** [comment]
原来是如此简单的 ^^" 谢谢大大的指点
