### ISSUE TITLE
一天會有3個子時1個丑時

### ISSUE THREAD

**Issue by cooliotseng** [hkargv/paipan#2]
可能是位元數的關係，我在chrome上跑會發生3個子時1個丑時
解法是我再算GetGZ時，在當中的
var spcjd = this.Jdays(yy, mm, dd, hh, mt, ss);
加了一個0.000000001
變成
var spcjd = this.Jdays(yy, mm, dd, hh, mt, ss)+0.000000001;
我是覺得這誤差應該是還好，不知你的想法。

**Comment by ghost** [comment]
你是说一天当中的整点有3个子时1个丑时吗?
p.GetGZ(2020,8,7,23,0,0); //子时
p.GetGZ(2020,8,8,0,0,0); //子时
p.GetGZ(2020,8,8,1,0,0); //丑时
p.GetGZ(2020,8,8,2,0,0); /丑时
p.GetGZ(2020,8,8,3,0,0); //寅时

没有问题不?

**Comment by cooliotseng** [comment]
這是從程式網頁直接跑的結果的截圖(子時換日)
你是用什麼方法跑Javascript的程式?
我測試是每天都一樣的結果
我也用IDEA將Javascript load到JAVA上去跑也是一樣的結果

![31](https://user-images.githubusercontent.com/12107510/89751155-80c3fe80-db01-11ea-99ef-31f37d532cd3.png)

**Comment by ghost** [comment]
确实有点问题
从技术角度,我得去请教一下bieyu.com的作者看怎么调整
从实际角度,古人对这一秒应该没这么精准,我觉得可以暂时用你这个方法修复

**Comment by cooliotseng** [comment]
了解，感謝你的回覆

**Comment by ghost** [comment]
bieyu.com作者的答复:
这与程序计算的方法有关，有些情况是从正方向算过来，有些情况是从反方向算过来。1，7，13，19时都有同样的问题，你若将分钟填入0.001，就正确了。有谁能肯定他出生的时刻是在1点0分0秒出生?所以若出生时间在整点时，我都会加个1分，以避开上面的那几个奇点。
