### ISSUE TITLE
php语法不够严谨，开启debug后，满屏 Warning

### ISSUE THREAD

**Issue by swling** [hkargv/paipan#3]
如题，虽然这些警告使用者自己可以修复，但还是建议作者考虑修复下。

**Comment by ghost** [comment]
谢谢.我把你的修复merge过来了,不知道是不是这么操作

目前网上最精确的应该属 寿星万年历 了
其农历部分在天文历法的基础上进行了手工核对,但只有js版本 http://www.nongli.net/sxwnl/

**Comment by swling** [comment]
> 
> 
> 谢谢.我把你的修复merge过来了,不知道是不是这么操作
> 
> 目前网上最精确的应该属 寿星万年历 了
> 其农历部分在天文历法的基础上进行了手工核对,但只有js版本 http://www.nongli.net/sxwnl/

哈哈哈，我也是第一次在github提交，但好像和我想的不一样，我之前指向简单修复下语法。后面好多提交比如，【类重命名】等等，都是我根据自己的喜好做的修改，但好像一起都合并过来了。哈哈哈。
