### ISSUE TITLE
流年中的year有问题？

### ISSUE THREAD

**Issue by onefishum** [hkargv/paipan#5]
p.fatemaps(0, 1980, 1, 1, 0, 0, 0);
结果：
dy: Array(9)
0: Array(0)
eyear: 1997
ly: Array(10)
0: [age: 10, year: 1997, lyean: 4, lyebn: 4, lye: '戊辰']   // 应该公历1988年，后面都是错的。。。
1: [age: 11, year: 1998, lyean: 5, lyebn: 5, lye: '己巳']
2: [age: 12, year: 1999, lyean: 6, lyebn: 6, lye: '庚午']
3: [age: 13, year: 2000, lyean: 7, lyebn: 7, lye: '辛未']
4: [age: 14, year: 2001, lyean: 8, lyebn: 8, lye: '壬申']
5: [age: 15, year: 2002, lyean: 9, lyebn: 9, lye: '癸酉']

**Comment by ghost** [comment]
确实是有问题,已经修正
